### PR TITLE
add scalajs support

### PR DESCRIPTION
**Pull request by pepegar**
fixes https://github.com/tpolecat/atto/issues/49

### CODE REVIEW

**Comment by tpolecat** [comment]
Wow this is great! Thank you. I will give it a try on the plane tomorrow.

**Comment by tpolecat** [comment]
The scala-js plugin creates a bunch of empty directories including a top-level `src/` tree and `.js` and `.jvm` dirs within each module. Do you know how to turn that off?

**Comment by tpolecat** [comment]
Would you mind upgrading scalacheck to `1.13.4` on your branch? It builds in CI but not locally for some reason, and upgrading seems to fix it.

I published `0.5.2-SNAPSHOT` from your branch to make sure that stuff works, and it seems fine. But can you take a look [here](https://oss.sonatype.org/content/repositories/snapshots/org/tpolecat/) and verify that the expected artifacts are there, with the correct names? Looks ok to me but I'm not very familiar with Scala-JS so another set of eyes would be helpful.

otherwise 👍 👍  👍

**Comment by pepegar** [comment]
Hi!

Regarding all the hidden folders that ScalaJS creates... that's the normal way, I think. ScalaJS creates that for using hidden folders as the true project's root in terms of SBT.

As for the artifacts, everything seems correct.

**Pull request merged**
