### PR TITLE
update compat to cats-0.7.2 in 0.5.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by felher**
Aloha :)
Do you mind updating the 0.5.0-SNAPSHOT to use the latest cats version?

### CODE REVIEW

**Comment by tpolecat** [comment]
Thanks! Will do.

**Comment by tpolecat** [comment]
@felher FYI - I think I may switch atto to use the approach I'm using with doobie, which is a preprocessor that compiles everything "natively" without requiring shims.

**Comment by tpolecat** [comment]
Ok the new snapshot should be out there.

**Comment by felher** [comment]
@tpolecat Great, thanks! :)
Why do you want to switch away from shims? Not that I have anything against it. Just curious if there are any non-obvious problems.

**Comment by tpolecat** [comment]
Technically it's ok but it imposes extra work on the user, which I don't want to do. I see compatibility as the library author's problem, not something the user should have to think about.

**Comment by felher** [comment]
@tpolecat I understand.
Speaking of compatibility: Truly sorry to bug you again, but did you also publish the compat-cats part?  [Here](https://oss.sonatype.org/#nexus-search;gav~org.tpolecat~atto-compat-cats_2.11~0.5.0-SNAPSHOT~~) it seems that the depedency of the compat is cats 0.5.0 (can be checked by clicking on "pom" on the left).

**Comment by tpolecat** [comment]
hell. i'll look at it in the morning

**Pull request merged**
